services:
  db:
    image: mysql:8
    container_name: tiffino-db
    restart: always
    environment:
      MYSQL_DATABASE: tiffino_db
      MYSQL_ROOT_PASSWORD: "Bullet@983"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Tiffino
      dockerfile: Dockerfile
    image: tiffino-backend:latest
    container_name: tiffino-backend
    restart: always
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tiffino_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bullet@983
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/Tiffino
      dockerfile: Dockerfile
    image: tiffino-frontend:latest
    container_name: tiffino-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:

